### ISSUE TITLE
No price updates or emails since July 3rd

### ISSUE THREAD

**Issue by micahpharoh** [VoDoo-Studios/unrealsales-tracker#76]
The tracker prices haven't updated in weeks and I also haven't been receiving emails. Last email was on July 3rd.

**Comment by CGeorges** [comment]
Thank you, I've rectified the error and updates should come up soon.

**Comment by micahpharoh** [comment]
It seems to have stopped updating again

**Comment by micahpharoh** [comment]
I just want to say that I've used your site a lot and I really appreciate your work. It's definitely been useful and I miss it a lot now that it's gone :(

**Comment by CGeorges** [comment]
Thank you @micahpharoh for your support. We had to switch servers and had some errors to solve. I believe it should be finally fixed now.

**Comment by micahpharoh** [comment]
Thank you <3

**Comment by micahpharoh** [comment]
I think it's down again
